import {useMemo} from 'react';
import {ArrowUpRight, ArrowRight, Check, CircleHelp} from 'lucide-react';
import type {OpportunityAnalysis} from '../../types';
import {calculateCompetitivePosition} from '../../domain/ptw/competitivePosition';
const money=(v:number|null)=>v==null?'Price basis needs clarification':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);
export default function CompetitiveRecommendation({analysis}:{analysis:OpportunityAnalysis}) {
  const p=useMemo(()=>calculateCompetitivePosition(analysis),[analysis]);
  const marker=p.target!=null && p.rangeLow!=null && p.rangeHigh!=null && p.rangeHigh>p.rangeLow?Math.min(98,Math.max(2,100*(p.target-p.rangeLow)/(p.rangeHigh-p.rangeLow))):50;
  const drivers=p.judgment.filter(j=>['Government evaluation','Labor and unit-price evidence','Predecessor / comparables'].includes(j.factor));
  const movers=[...p.sensitivities].sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta)).slice(0,3);
  return <article aria-label="Executive pricing decision" className="max-w-5xl mx-auto space-y-8">
    {analysis.meta.packageCoverage?.mode==='HISTORICAL'&&<p className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">{analysis.historical?`Historical test · As of ${analysis.historical.cutoff} · ${analysis.historicalReview?'Validated backtest — independent review recorded':'Retrospective approximation pending independent evidence review' }. ${analysis.frozenPrediction?'Original prediction frozen.':''}`:'Legacy historical practice · Current research was used; not a historical backtest.'}</p>}
    <section className="relative overflow-hidden rounded-2xl bg-[#103243] text-white px-6 py-8 sm:px-9 sm:py-10">
      <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs font-bold uppercase tracking-[.2em] text-teal-200">Your competitive position</p><span className="text-xs rounded-full border border-white/25 px-3 py-1.5">{p.assumptionShare>0?'Assumption-led recommendation':'Evidence-led recommendation'}</span></div>
      <h2 className="mt-7 text-base font-medium text-slate-200">Where should we price?</h2>
      <p className="mt-2 font-bold tracking-tight text-4xl sm:text-6xl break-words" data-testid="recommended-ptw">{money(p.target)}</p>
      <p className="mt-2 text-sm text-teal-100">Recommended PTW · Government evaluated price</p>
      {p.target!=null && <div className="mt-7 pt-6 border-t border-white/20"><div className="flex flex-wrap items-baseline justify-between gap-2"><span className="text-xs uppercase tracking-wider text-slate-300">Competitive corridor</span><strong className="text-lg" data-testid="competitive-corridor">{money(p.rangeLow)} – {money(p.rangeHigh)}</strong></div><div aria-hidden="true" className="relative mt-4 h-1 rounded bg-white/20"><span className="absolute -top-1.5 h-4 w-1 bg-teal-200" style={{left:`${marker}%`}}/></div><p className="mt-4 max-w-3xl text-xs leading-5 text-slate-300">{p.rangeMeaning}</p></div>}
      {p.target==null && <p className="mt-5 text-sm leading-6 text-amber-100">{p.decisionRequest} {p.missing[0]}</p>}
    </section>
    <section className="grid gap-7 md:grid-cols-[1.15fr_1fr] border-b border-slate-200 pb-8">
      <div><h2 className="text-lg font-bold">Why this position?</h2><p className="mt-3 text-sm leading-6 text-slate-700">{p.rationale}</p><ul className="mt-4 space-y-3">{drivers.map(d=><li key={d.factor} className="flex gap-3"><Check className="mt-1 h-4 w-4 shrink-0 text-teal-700"/><span className="text-sm leading-6 text-slate-600">{d.finding}</span></li>)}</ul></div>
      <div className="rounded-xl bg-[#edf3f3] p-6"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Recommendation Confidence</p><h2 className="mt-2 text-2xl font-bold text-[#103243]" data-testid="recommendation-confidence">{p.confidenceLabel.charAt(0)+p.confidenceLabel.slice(1).toLowerCase()}</h2><p className="mt-3 text-sm leading-6 text-slate-700">{p.confidenceReason}</p><p className="mt-4 text-xs leading-5 text-slate-500">Confidence describes support for this recommendation. It is not a win probability or a score of your company.</p></div>
    </section>
    <section><h2 className="text-lg font-bold">What could move it?</h2><div className="mt-4 divide-y divide-slate-200 border-y border-slate-200">{movers.length?movers.map(s=><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 py-4" key={s.label+s.change}><div><p className="text-sm font-semibold">{s.label}</p><p className="mt-1 text-xs text-slate-500">{s.change}</p></div><span className="inline-flex items-center gap-1 text-lg font-semibold text-[#103243]"><ArrowUpRight className="h-4 w-4"/>{money(s.delta)}</span></div>):<p className="py-4 text-sm text-slate-600">The corridor bounds represent alternative price assumptions. Validate the largest component first.</p>}</div></section>
    <section className="rounded-xl border border-teal-200 bg-white p-6"><div className="flex gap-3"><ArrowRight className="mt-1 h-5 w-5 shrink-0 text-teal-700"/><div><h2 className="text-lg font-bold">What should we do next?</h2><p className="mt-2 text-sm leading-6 text-slate-700">{p.actions[0]?.action}</p><p className="mt-2 text-xs text-slate-500">Owner: {p.actions[0]?.owner}. {p.actions[0]?.consequence}</p></div></div></section>
    {analysis.meta.packageCoverage&&<details className="rounded-xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer text-sm font-semibold">Source coverage · {analysis.meta.packageCoverage.documents.length} files · Latest amendments unverified</summary><p className="mt-3 text-xs leading-6 text-slate-500">{analysis.meta.packageCoverage.freshness.message}</p><ul className="mt-4 divide-y divide-slate-100">{analysis.meta.packageCoverage.documents.map(d=><li key={d.id} className="py-3 text-xs leading-5"><strong className="break-words">{d.name}</strong><p className="text-slate-500">{d.status} · {d.categories.join(', ')||'Supporting material'}</p>{d.note&&<p className="text-amber-800">{d.note}</p>}</li>)}</ul></details>}
    <p className="flex gap-2 text-xs leading-5 text-slate-500"><CircleHelp className="mt-0.5 h-4 w-4 shrink-0"/>A market pricing recommendation, subject to its assumptions. Company costs, margin and final bid approval remain separate.</p>
  </article>;
}
