import {useState} from 'react';
import type {OpportunityAnalysis} from '../../types';
import {calculateCompetitivePosition,validPlanningInput} from '../../domain/ptw/competitivePosition';
export default function PlanningAssumptions({analysis,onUpdate}:{analysis:OpportunityAnalysis;onUpdate:(a:OpportunityAnalysis)=>Promise<void>}){
  const [inputs,setInputs]=useState(()=>calculateCompetitivePosition(analysis).planningRows);
  const [saving,setSaving]=useState(false),[message,setMessage]=useState('');
  if(!inputs.length)return null;
  const save=async()=>{if(inputs.some(p=>!validPlanningInput(p))){setMessage('Every bound must be positive and ordered lower ≤ central ≤ upper, with a rationale.');return;}setSaving(true);try{await onUpdate({...analysis,deal:{...analysis.deal,planningInputs:inputs}});setMessage('Recommendation and corridor recalculated from the updated assumptions.');}catch(e){setMessage(e instanceof Error?e.message:'Save failed.');}finally{setSaving(false);}};
  return <section className="rounded-xl border border-teal-200 bg-white p-5 mb-6"><h2 className="text-lg font-bold">Recommendation assumptions</h2><p className="mt-2 text-sm text-slate-600">Changes here recalculate Recommended PTW and its corridor. Document the reason for each change.</p><div className="mt-5 space-y-5">{inputs.map((p,index)=><fieldset className="border-t pt-4" key={p.id}><legend className="font-semibold text-sm">{p.label} · {p.unit}</legend><div className="mt-2 grid grid-cols-3 gap-3">{(['low','central','high'] as const).map(key=><label key={key} className="text-xs text-slate-600">{key==='low'?'Lower':key==='central'?'Central':'Upper'}<input aria-label={`${p.label} ${key}`} type="number" min="0" value={p[key]} onChange={e=>setInputs(current=>current.map((v,i)=>i===index?{...v,[key]:Number(e.target.value)}:v))} className="block mt-1 w-full min-w-0 rounded border p-2.5 text-sm"/></label>)}</div><label className="mt-3 block text-xs text-slate-600">Assumption rationale<textarea value={p.rationale} onChange={e=>setInputs(current=>current.map((v,i)=>i===index?{...v,rationale:e.target.value,basis:'PLANNING_ASSUMPTION'}:v))} className="mt-1 block w-full rounded border p-3 text-sm"/></label></fieldset>)}</div><button onClick={save} disabled={saving} className="mt-5 rounded-lg bg-teal-800 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{saving?'Recalculating…':'Recalculate recommendation'}</button>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}</section>;
}
