import {ArrowRight,FolderOpen} from 'lucide-react';
interface Props {runCount:number;onStart:()=>void;onOpenRuns:()=>void}
export default function LandingHero({runCount,onStart,onOpenRuns}:Props){
  return <div className="mx-auto max-w-7xl px-5 py-12 sm:px-8 sm:py-20">
    <section className="grid items-center gap-12 lg:grid-cols-[1.1fr_1fr] lg:gap-20">
      <div><p className="fmp-eyebrow">Federal pricing intelligence</p><h1 className="mt-5 max-w-2xl text-5xl font-semibold leading-[1.08] tracking-[-.045em] sm:text-6xl">A clear position.<br/><span className="text-teal-700">A defensible price.</span></h1><p className="mt-7 max-w-lg text-lg leading-8 text-slate-600">Turn a solicitation package into a pricing decision your team can challenge, understand, and act on.</p><div className="mt-8 flex flex-wrap gap-3"><button className="fmp-primary" onClick={onStart}>Upload solicitation package<ArrowRight size={18}/></button>{runCount>0&&<button className="fmp-secondary" onClick={onOpenRuns}><FolderOpen size={17}/>Saved decisions · {runCount}</button>}</div><p className="mt-4 text-xs leading-5 text-slate-500">Start with a SAM.gov ZIP or individual documents. No SAM lookup required.</p></div>
      <aside className="rounded-2xl bg-[#103243] p-7 text-white sm:p-10"><p className="text-xs font-semibold uppercase tracking-[.18em] text-teal-200">Your executive brief</p><h2 className="mt-5 text-2xl font-medium leading-9">Five questions.<br/>One pricing decision.</h2><ol className="mt-7 divide-y divide-white/15">{['Where should we price?','Why this position?','How confident are we?','What could move it?','What should we do next?'].map((q,i)=><li className="flex items-center gap-4 py-4 text-sm" key={q}><span className="font-mono text-xs text-teal-200">0{i+1}</span>{q}</li>)}</ol><p className="mt-5 text-xs leading-5 text-slate-300">The recommendation stays simple. Source evidence, assumptions, and calculations stay available underneath.</p></aside>
    </section>
    <section className="mt-16 border-t border-slate-200 pt-8 sm:mt-20"><div className="grid gap-7 sm:grid-cols-3">{[['Bring the whole package','ZIP intake inventories every file and prioritizes the documents that drive evaluated price.'],['Understand the uncertainty','Explicit assumptions and recommendation confidence show where judgment still matters.'],['Take the decision with you','Share the executive PDF or inspect the detailed pricing workbook.']].map(([title,description],i)=><div key={title}><span className="text-xs font-semibold text-teal-700">0{i+1}</span><h2 className="mt-3 text-base font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></div>)}</div></section>
  </div>;
}
