import { ArrowRight, Clock3, FilePlus2, Trash2 } from 'lucide-react';
import type { OpportunityAnalysis } from '../types';
interface Props { runs: OpportunityAnalysis[]; onSelect: (id: string) => void; onNew: () => void; onDelete: (id: string) => void; onImport?: () => void; }
const money = (value: number | null) => value === null ? 'Pending evidence' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', notation: 'compact', maximumFractionDigits: 1 }).format(value);
export default function OpportunityRuns({ runs, onSelect, onNew, onDelete, onImport }: Props) {
  return <div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">Your workspace</p><h1 className="mt-2 text-3xl font-black tracking-tight">Pricing decisions</h1><p className="mt-2 text-sm text-slate-500">Saved in your private workspace.</p><a href="/api/historical-scorecard.csv" className="mt-2 inline-block text-xs font-bold text-teal-700 underline">Download historical test scorecard</a>{onImport && <button onClick={onImport} className="mt-2 text-xs font-bold text-teal-700 underline">Import older runs from this browser</button>}</div><button onClick={onNew} className="rounded-xl bg-[#146c62] px-4 py-2.5 text-xs font-black text-white">New analysis</button></div>
    {runs.length === 0 ? <div className="mt-12 rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-20 text-center"><FilePlus2 className="mx-auto h-9 w-9 text-slate-300" /><h2 className="mt-4 text-lg font-black">No analyses yet</h2><p className="mt-2 text-sm text-slate-500">Upload a solicitation ZIP or individual documents to create your first pricing recommendation.</p><button onClick={onNew} className="mt-6 rounded-xl bg-[#10243e] px-5 py-3 text-xs font-black text-white">Upload package</button></div>
    : <div className="mt-8 grid gap-4 lg:grid-cols-2">{(runs || []).filter(Boolean).map((run) => <article key={run.id} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><span className="text-[10px] font-black uppercase tracking-[.16em] text-teal-700">{run.deal?.agency}</span><h2 className="mt-2 line-clamp-2 text-lg font-semibold">{run.deal?.title}</h2><p className="mt-1 text-xs font-semibold text-slate-400">{run.deal?.solicitationNumber}</p></div>{!run.frozenPrediction&&<button onClick={() => onDelete(run.id)} aria-label="Delete analysis" className="rounded-lg p-2 text-slate-300 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4" /></button>}</div><div className="mt-6 grid grid-cols-3 gap-3 border-y border-slate-100 py-4"><div><span className="block text-[10px] font-bold uppercase text-slate-400">Recommended PTW</span><strong className="mt-1 block text-sm">{run.competitivePosition?.target != null ? money(run.competitivePosition.target) : 'Pending'}</strong></div><div><span className="block text-[10px] font-bold uppercase text-slate-400">Confidence</span><strong className="mt-1 block text-sm">{run.competitivePosition?.confidenceLabel || 'Limited'}</strong></div><div><span className="block text-[10px] font-bold uppercase text-slate-400">Status</span><strong className="mt-1 block text-sm">{run.competitivePosition?.assumptionShare ? 'Assumption-led' : 'Evidence-led'}</strong></div></div><div className="mt-4 flex items-center justify-between"><span className="inline-flex items-center gap-1.5 text-xs text-slate-400"><Clock3 className="h-3.5 w-3.5" />{run.meta?.analyzedAt ? new Date(run.meta.analyzedAt).toLocaleDateString() : ''}</span><button onClick={() => onSelect(run.id)} className="inline-flex items-center gap-2 text-xs font-black text-teal-700">Open brief <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></button></div></article>)}</div>}
  </div>;
}
