import { ArrowRight, Clock3, FilePlus2, Trash2 } from 'lucide-react';
import type { OpportunityAnalysis } from '../types';
interface Props { runs: OpportunityAnalysis[]; onSelect: (id: string) => void; onNew: () => void; onDelete: (id: string) => void; }
const money = (value: number) => value ? new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', notation: 'compact', maximumFractionDigits: 1 }).format(value) : 'Pending evidence';
export default function OpportunityRuns({ runs, onSelect, onNew, onDelete }: Props) {
  return <div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">Analysis library</p><h1 className="mt-2 text-3xl font-black tracking-tight">Opportunity runs</h1><p className="mt-2 text-sm text-slate-500">Saved locally in this browser.</p></div><button onClick={onNew} className="rounded-xl bg-[#1167e8] px-4 py-2.5 text-xs font-black text-white">NEW RUN</button></div>
    {runs.length === 0 ? <div className="mt-12 rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-20 text-center"><FilePlus2 className="mx-auto h-9 w-9 text-slate-300" /><h2 className="mt-4 text-lg font-black">No analyses yet</h2><p className="mt-2 text-sm text-slate-500">Upload one solicitation to create the first market-position brief.</p><button onClick={onNew} className="mt-6 rounded-xl bg-[#10243e] px-5 py-3 text-xs font-black text-white">START ANALYSIS</button></div>
    : <div className="mt-8 grid gap-4 lg:grid-cols-2">{runs.map((run) => <article key={run.id} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><span className="text-[10px] font-black uppercase tracking-[.16em] text-blue-600">{run.deal.agency}</span><h2 className="mt-2 truncate text-lg font-black">{run.deal.title}</h2><p className="mt-1 text-xs font-semibold text-slate-400">{run.deal.solicitationNumber}</p></div><button onClick={() => onDelete(run.id)} aria-label="Delete analysis" className="rounded-lg p-2 text-slate-300 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4" /></button></div><div className="mt-6 grid grid-cols-3 gap-3 border-y border-slate-100 py-4"><div><span className="block text-[10px] font-bold uppercase text-slate-400">Target</span><strong className="mt-1 block text-sm">{money(run.marketPosition.target)}</strong></div><div><span className="block text-[10px] font-bold uppercase text-slate-400">Confidence</span><strong className="mt-1 block text-sm">{run.marketPosition.confidenceScore}%</strong></div><div><span className="block text-[10px] font-bold uppercase text-slate-400">Mode</span><strong className="mt-1 block text-sm">{run.meta.mode === 'MARKET_ONLY' ? 'Market' : 'Company'}</strong></div></div><div className="mt-4 flex items-center justify-between"><span className="inline-flex items-center gap-1.5 text-xs text-slate-400"><Clock3 className="h-3.5 w-3.5" />{new Date(run.meta.analyzedAt).toLocaleDateString()}</span><button onClick={() => onSelect(run.id)} className="inline-flex items-center gap-2 text-xs font-black text-blue-700">OPEN BRIEF <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></button></div></article>)}</div>}
  </div>;
}
