import {readFileSync, writeFileSync} from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
let source='// Generated by scripts/embed-fonts.mjs. Inter is licensed under OFL-1.1; see FONT-LICENSE.txt.\n';
for(const [name,weight] of [['regular',400],['bold',700]]) source+=`export const ${name}FontData = '${readFileSync(require.resolve(`@fontsource/inter/files/inter-latin-${weight}-normal.woff`)).toString('base64')}';\n`;
writeFileSync('src/exports/fontData.ts',source);
writeFileSync('src/exports/FONT-LICENSE.txt',readFileSync('node_modules/@fontsource/inter/LICENSE'));
